name: ci

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*' # don't run ci on tags, should already have run on commit tag points to.
    paths-ignore:
      - README.md # don't run for readme changes.
  schedule:
    - cron: '0 0 * * 1' # Every monday at midnight

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install ruby dependencies
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install
    - name: Install brew dependencies
      run: |
        brew install coreutils
    - name: Tests
      run: |
        bundle exec rspec
    - name: Lint
      run: |
        bundle exec rubocop