name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Upload Release Assets
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GitHub automatically creates a GITHUB_TOKEN secret to use in your workflow.
          # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true